version: '3.5'
services:
# Set up NameNode and Spark Master
  sparkmaster:
    image: rmuresano/bdaassparkmaster:0_0_1
    hostname: sparkmaster
    environment:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - HDFS_NAMENODE_METADATA_PORT=9000
      - HDFS_CLUSTER_NAME=HDFS_TEST
      - HDFS_NAMENODE_WEBUI_PORT=50070
      - HDFS_REPLICATION_FACTOR=1
      - HDFS=YES
    ports:
      - "8080:8080" #Web Interface Master
      - "7077:7077" #Master Port
      - "9000:9000" # HDFS PORT
      - "50070:50070" # WEB NameNode Int
    volumes:
      - hdfs-name-node:/hdfsdata/nameNode/
    placement:
        constraints: [node.hostname != manager-bdaas]
# Setup the Worker Node 1.
  sparkworker:
    image: rmuresano/bdaassparkworker:0_0_1
    hostname: sparkworker
    depends_on:
      - sparkmaster
    environment:
      - SPARK_MASTER_HOSTNAME=sparkmaster
      - SPARK_MASTER_PORT=7077
      - HDFS_NAMENODE_HOSTNAME=sparkmaster
      - HDFS_NAMENODE_METADATA_PORT=9000
      - HDFS_REPLICATION_FACTOR=1
      - HDFS_DATANODE_WEBUI_PORT=50075
      - SPARK_WORKER_WEBUI_PORT=8081
      - HDFS_NAMENODE_WEBUI_PORT=50070
      - HDFS=YES
    ports:
      - "8081-8090:8081"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname != manager-bdaas]
    
  jupyter:
    image: rmuresano/bdaasjupyter:0_0_1
    hostname: jupyter
    depends_on:
      - sparkmaster
    environment:
      - STANDALONE=NO
      - JUPYTERPORT=8901
      - HDFS=YES
      - HDFS_NAMENODE_HOSTNAME=sparkmaster
      - HDFS_DATANODE_WEBUI_PORT=50075
      - HDFS_NAMENODE_METADATA_PORT=9000
      - HDFS_REPLICATION_FACTOR=1
      - SPARK_MASTER_HOSTNAME=sparkmaster
      - SPARK_MASTER_PORT=7077
    ports:
      - "8901:8901" # WEB interface JupyterLab
    volumes:
      - jupyter-vol:/data/jupyter/
    deploy:
      placement:
        constraints: [node.hostname != manager-bdaas]

volumes:
  jupyter-vol:
  hdfs-name-node:
  hdfs-data-node: