version: '3'
services:
  jupyter1:
    image: rmuresano/bdaasjupyter:0_0_4
    hostname: jupyter1
    container_name: jupyter1
    environment:
      - STANDALONE=YES
      - JUPYTERPORT=8900
      - HDFS=NO
    ports:
      - "10000:8900" # WEB interface JupyterLab
    volumes:
      - jupyter-vol:/data/jupyter/

volumes:
  jupyter-vol:
