version: '3'
services:
  jupyter:
    image: rmuresano/bdaasjupyter:0_0_4
    hostname: jupyter
    container_name: jupyter
    environment:
      - STANDALONE=YES
      - JUPYTERPORT=8900
      - HDFS=NO
    ports:
      - "8900:8900" # WEB interface JupyterLab
    volumes:
      - jupyter-vol:/data/jupyter/

volumes:
  jupyter-vol:
