version: '3'

services:
  neo4j:
    image: rmuresano/bdaasneo4j:0_0_4"
    container_name: neo4j
    environment:
      - NEO4J_BOLT_PORT=7687
      - NEO4J_WEBUI_PORT=7474
      - PERSISTENT_VOLUME="/data/neo4j/"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes: 
      -  neo4j-vol:/data/neo4j/

volumes:
  neo4j-vol:
