version: '3'

services:
  cassandra-seed:
    image: components/bdaascassandra:0_0_1
    hostname: cassandra-seed
    container_name: cassandra-seed-node
    environment:
      - CLUSTER_NAME=seminario
      - STORAGE_PORT=7000
      - START_NATIVE_TRANSPORT=TRUE
      - NATIVE_TRANSPORT_PORT=9042
      - RPC_PORT=9160
    networks:
      cassandra:
        ipv4_address: 172.28.1.2

  cassandra-node:
    image: components/bdaascassandra:0_0_1
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-node
      - CLUSTER_NAME=seminario
      - STORAGE_PORT=7000
      - START_NATIVE_TRANSPORT=TRUE
      - NATIVE_TRANSPORT_PORT=9042
      - RPC_PORT=9160
    depends_on:
      - cassandra-seed
    networks:
      cassandra:
        ipv4_address: 172.28.1.3
  jupyter:
    image: components/bdaasjupyter:0_0_1
    container_name: jupytercassandra
    environment:
      - STANDALONE=YES
      - HDFS=NO
      - CASSANDRA=YES
      - JUPYTERPORT=8900
      - CASSANDRA_HOSTNAME=cassandra-seed
      - REPLICATION_FACTOR=1
      - CASSANDRA_SEEDS=172.28.1.2
    networks:
      cassandra:
        ipv4_address: 172.28.1.1

    ports:
      - "8900:8900"
    depends_on:
      - cassandra-seed
    volumes:
      - jupyter-vol:/data/jupyter/

volumes:
  jupyter-vol:
    
networks:
  cassandra:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
