apiVersion: v1
kind: Service
metadata: 
  name: jupyter-notebook
  labels: 
    name: jupyter-notebook
spec:
  ports: 
    - protocol: TCP
      port: 8888 # 
      targetPort: 8888
  selector:
    name: jupyter-notebook