apiVersion: v1
kind: Service
metadata:
  name: idolized-tapir-node-red
spec:
  selector:
    app: nodered
  ports:
  - protocol: TCP
    port: 1880 #
    targetPort: 1880
  type: LoadBalancer


  #export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,release=grafana" -o jsonpath="{.items[0].metadata.name}")
  #kubectl --namespace default port-forward $POD_NAME 3000 &
